### PR TITLE
Allow filtering hangs based on their annotations

### PR DESCRIPTION
**Pull request by squarewave**
This isn't intended as a final version of this feature, because obviously there's no UI, and some polish would be necessary to make it clear to users what is being filtered and how. However, it's intended to be enough to explore the data with these filters and see if we see anything interesting.

### CODE REVIEW

**Comment by squarewave** [comment]
Quick explanation of how to use this, so you don't have to read the code to figure it out: a query string like `#date=20210519&row=0&annotations=UserInteracting:true` should do the trick.

**Comment by squarewave** [comment]
Updated: `#date=20210519&row=0&annotations=UserInteracting:true,!ExternalCPUHigh:true`

**Comment by fqueze** [comment]
> This isn't intended as a final version of this feature, because obviously there's no UI, and some polish would be necessary to make it clear to users what is being filtered and how. However, it's intended to be enough to explore the data with these filters and see if we see anything interesting.

Were you sharing the PR so that I can play with it too, or would you like me to merge it as is? I reviewed the code and tested locally. It looks good to me for an experimental feature, and we can iterate on it later after exploring the data for a few days.

If we want to polish this further:
- I think the title could look better. I would prefer "UserInteracting: true, NOT ExternalCPUHigh" instead of "UserInteracting: true - ExternalCPUHigh NOT true"
- it would be nice to support providing a key without the value. Eg if I want to see hangs while opening tabs, I might not care about whether it was animated or not, and specifying all the key&value pairs will make the URL really long.
- (much harder to do given the current code) it would be nice to be able to see the result of a filter without needing to reload the entire page, but that means we would need to filter at display time rather than at fetch time.

**Comment by squarewave** [comment]
All right. I addressed bullets one and two. Regarding filtering at display time, I think you're right that we should do that if we want to support this fully, but it's a little bit hairier than I think is worth implementing right now.

**Comment by fqueze** [comment]
Thanks, let's use this for a while and see how much value it provides to decide if we want to add UI for it.

**Pull request merged**
